/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Red Fox / nokillnando (https://sketchfab.com/nokillnando)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-f34c1400926e430a9ef10bb180986b42
Title: Laptop
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/laptop/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.LaptopKeys}
            />
            <mesh
              geometry={nodes.defaultMaterial_3.geometry}
              material={materials.LaptopBack}
            />
            <mesh
              geometry={nodes.defaultMaterial_4.geometry}
              material={materials.LaptopFront}
            />
          </group>
          <group
            position={[0, 0.626, -12]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.LaptopScreen}
            />
            <mesh
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.LaptopBack}
            />
            <mesh
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.LaptopFront}
            />
          </group>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.LaptopKeys}
            position={[-3.419, 0.779, -0.907]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.LapTopMisc}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
